### ISSUE TITLE
Pythonwin not showing the file to edit

### ISSUE THREAD

**Issue by desb42** [mhammond/pywin32#1269]
On a new Windows 10 computer I have installed Python 3.71 and pywin32 224 (64bit)
When I right click on a file in Explorer and select 'Edit with pythonwin'
pythonwin starts with the Interactive edit window but not the file I wish to edit

I have tried this on another Windows box with the 32 bit version with the same results

Could it be to do with v3.71?

**Comment by bgoodmansf** [comment]
I'm having the same problem. I have used PythonWin for years on Python 2.x and 3.6.

Just updated several systems to Python 3.7.3.

On Windows 7 and Windows 10 the File Explorer "Edit with PythonWin" context menu launches PythonWin, but the selected document is not opened.

Furthermore, on Windows 7 drag-and-drop of a file onto a running PythonWin will display the file. But doing the same thing on Windows 10 does not open the file.

The only way I have found to open a file on Windows 10 is to launch PythonWin and then use the Open menu command.

On one of the Windows 10 systems, I have started seeing a failure when PythonWin is launched from the Start menu:
Traceback (most recent call last):
  File "C:\Program Files\Python37\Lib\site-packages\pythonwin\pywin\framework\intpyapp.py", line 156, in InitDDE
if self.ProcessArgs(sys.argv, connection) is None:
  File "C:\Program Files\Python37\Lib\site-packages\pythonwin\pywin\framework\intpyapp.py", line 228, in ProcessArgs
if dde is not None: dde.Exec("self.Activate()")
dde.error: Exec failed


On all systems, PythonWin was installed from a binary. I think the installer was run as administrator in all cases, but I am not positive about that.

**Comment by bgoodmansf** [comment]
Forgot to mention that all installs were done "for all users" so they are in C:\Program Files\Python37.

**Comment by 1fatuheeva** [comment]
I have the same problem. Windows 10 with Python 3.7.3. Tried installing with pywin32-224.win-amd64-py3.7.exe
and also pip.
I recognize this is a minor inconvenience but it would be nice to have some official guidance. Do I need to run Python 3.6 instead?
Thanks

**Comment by desb42** [comment]
Just to see if anything had changed I installed Python 3.8 (x64) and pywin32-227 on to a Windows 10 machine that only had Python 2.7.12 (x32)

The issue is the same - Pythonwin as an environment starts but no file to edit

It seems that sys.argv is not being populated

If I put `win32ui.MessageBox("here" + repr(sys.argv))` at the begging of startup.py
I get a popup `here['']`

Could something have happen on the CPython side of things?

**Comment by desb42** [comment]
On delving into this further, I came across some code in \Pythonwin\win32uimodule.cpp (part of win32ui.pyd) within the function Win32uiApplicationInit

    extern "C" PYW_EXPORT BOOL Win32uiApplicationInit(Win32uiHostGlue *pGlue, TCHAR *cmd, const TCHAR *additionalPaths)
    {
    #ifdef _DEBUG
        afxDump.SetDepth(1);  // deep dump of objects at exit.
        bool bDebug = true;
    #else
        bool bDebug = false;
    #endif
        // We need to ensure that _this_ instance of
        // win32ui is attached to Python - otherwise there is
        // a risk that when Python does "import win32ui", it
        // will locate a different one, causing obvious grief!
        PyObject *argv = PySys_GetObject("argv");
    #if (PY_VERSION_HEX < 0x03000000)
        initwin32ui();
        // Set sys.argv if not already done!
        if (argv == NULL && __targv != NULL && __argc > 0)
            PySys_SetArgv(__argc - 1, __targv + 1);
    #else
        PyInit_win32ui();
        if (argv == NULL) {
            int myargc;
            LPWSTR *myargv = CommandLineToArgvW(GetCommandLineW(), &myargc);
            if (myargv) {
                PySys_SetArgv(myargc - 1, myargv + 1);
                LocalFree(myargv);
            }
        }
    #endif
As of version 3.8.0 (but I suspect from versions above 3.7.0), the PySys_GetObject call returns a non NULL value, such that the PySys_SetArgv is necer called
This results in the behaviour I am getting

If I (crudely) don't call PySys_GetObject

        PyObject *argv = NULL;
hence argv is NULL - all works as expected (the command line arguments are processed)

**Comment by mhammond** [comment]
Thanks for digging in! That code is assuming that if Python already knows what `sys.argv` is, it is correct. I assume that you are finding it be an empty list (or list with 1 element)? If so, that implies the bug is actually in whatever is setting `sys.argv` in the first place?

**Comment by kxrob** [comment]
There was another issue with Python 3.8+ as compared to Python 3.7 . Should be fixed with PR #1622

**Comment by desb42** [comment]
Having got a new computer, I tried (yet again) to install the latest Python and Pythonwin
That is Python 3.9.5 and pywin32-b300
Still no luck - same error as mentioned

I see that @kxrob has made some changes (that ought to work) but for me they do not.
Once again, if I (crudely) don't call PySys_GetObject

    PyObject *argv = NULL;
everything behaves as I expect

**Comment by mhammond** [comment]
> I see that @kxrob has made some changes (that ought to work) but for me they do not.

This fix isn't in build 300.

> Once again, if I (crudely) don't call PySys_GetObject

To be clear, you mean that building the current git tip also doesn't work for you?

**Comment by desb42** [comment]
It seems I was not using the latest code (tip)
Using the latest snapshot the behaviour is correct (apologies for the confusion)

Do you have a timescale for your next release?
